services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./wp-content:/var/www/html/wp-content
      - ./plugins/wp-react-blocks-plugin:/var/www/html/wp-content/plugins/wp-react-blocks-plugin
      - ./plugins/wp-react-custom-rest-menu:/var/www/html/wp-content/plugins/wp-react-custom-rest-menu
      - ./plugins/wp-react-custom-multilang:/var/www/html/wp-content/plugins/wp-multilang
      - ./wp-theme:/var/www/html/wp-content/themes/dg-semantic

    depends_on:
      - wordpress

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./plugins/wp-react-blocks-plugin:/var/www/html/wp-content/plugins/wp-react-blocks-plugin
      - ./plugins/wp-react-custom-rest-menu:/var/www/html/wp-content/plugins/wp-react-custom-rest-menu
      - ./plugins/wp-react-custom-multilang:/var/www/html/wp-content/plugins/wp-multilang
      - ./wp-theme:/var/www/html/wp-content/themes/dg-semantic
    environment:
      environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.7-focal
    volumes:
      - mysql:/var/lib/mysql
    environment:
      YSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306

volumes:
  wordpress_data:
  mysql: