import {PanelRow, SelectControl, TextControl} from '@wordpress/components';
import {__} from '@wordpress/i18n';


const Format = ({format, title, onFormatChange}) => {


    const onChangeFormat = (style) => {
        onFormatChange(Object.assign({}, format, {style}))
    }

    const onDecimalChange = (value) => {
        onFormatChange(Object.assign({}, format, {
            minimumFractionDigits: value,
            maximumFractionDigits: value
        }))
    }
    const onCurrencyChange = (currency) => {
        
        onFormatChange(Object.assign({}, format, {currency}))
    }

    return [
        <PanelRow>
            <SelectControl
                label={__('Style',"dg")}
                value={[format.style]} // e.g: value = [ 'a', 'c' ]
                onChange={onChangeFormat}
                options={[
                    {label: 'Decimal', value: 'decimal'},
                    {label: 'Compacted', value: 'compacted'},
                    {label: 'Currency', value: 'currency'},
                    {label: 'Percent', value: 'percent'}
                ]
                }
            />
        </PanelRow>,
        <>{format.style === "currency" && <PanelRow>
            <SelectControl
                label={__("Currency","dg")}
                onChange={onCurrencyChange}
                value={format.currency}
                options={[
                    {"label": "ADB Unit of Account (XUA)", "value": "XUA"},
                    {"label": "Afghani (AFN)", "value": "AFN"},
                    {"label": "Afghani (AFA)", "value": "AFA"},
                    {"label": "Algerian Dinar (DZD)", "value": "DZD"},
                    {"label": "Andorran Peseta (ADP)", "value": "ADP"},
                    {"label": "Argentine Peso (ARS)", "value": "ARS"},
                    {"label": "Armenian Dram (AMD)", "value": "AMD"},
                    {"label": "Aruban Florin (AWG)", "value": "AWG"},
                    {"label": "Austral (ARA)", "value": "ARA"},
                    {"label": "Australian Dollar (AUD)", "value": "AUD"},
                    {"label": "Azerbaijan Manat (AZN)", "value": "AZN"},
                    {"label": "Azerbaijan Manat (AYM)", "value": "AYM"},
                    {"label": "Azerbaijanian Manat (AZM)", "value": "AZM"},
                    {"label": "Bahamian Dollar (BSD)", "value": "BSD"},
                    {"label": "Bahraini Dinar (BHD)", "value": "BHD"},
                    {"label": "Baht (THB)", "value": "THB"},
                    {"label": "Balboa (PAB)", "value": "PAB"},
                    {"label": "Barbados Dollar (BBD)", "value": "BBD"},
                    {"label": "Belarusian Ruble (BYN)", "value": "BYN"},
                    {"label": "Belarusian Ruble (BYB)", "value": "BYB"},
                    {"label": "Belarusian Ruble (BYR)", "value": "BYR"},
                    {"label": "Belgian Franc (BEF)", "value": "BEF"},
                    {"label": "Belize Dollar (BZD)", "value": "BZD"},
                    {"label": "Bermudian Dollar (BMD)", "value": "BMD"},
                    {"label": "Bol√≠var (VEF)", "value": "VEF"},
                    {"label": "Bol√≠var Soberano (VES)", "value": "VES"},
                    {"label": "Bolivar (VEB)", "value": "VEB"},
                    {"label": "Bolivar (VEF)", "value": "VEF"},
                    {"label": "Bolivar Fuerte (VEF)", "value": "VEF"},
                    {"label": "Boliviano (BOB)", "value": "BOB"},
                    {
                        "label": "Bond Markets Unit European Composite Unit (EURCO) (XBA)",
                        "value": "XBA"
                    },
                    {
                        "label": "Bond Markets Unit European Monetary Unit (E.M.U.-6) (XBB)",
                        "value": "XBB"
                    },
                    {
                        "label": "Bond Markets Unit European Unit of Account 17 (E.U.A.-17) (XBD)",
                        "value": "XBD"
                    },
                    {
                        "label": "Bond Markets Unit European Unit of Account 9 (E.U.A.-9) (XBC)",
                        "value": "XBC"
                    },
                    {"label": "Brazilian Real (BRL)", "value": "BRL"},
                    {"label": "Brunei Dollar (BND)", "value": "BND"},
                    {"label": "Bulgarian Lev (BGN)", "value": "BGN"},
                    {"label": "Burundi Franc (BIF)", "value": "BIF"},
                    {"label": "Cabo Verde Escudo (CVE)", "value": "CVE"},
                    {"label": "Canadian Dollar (CAD)", "value": "CAD"},
                    {"label": "Cayman Islands Dollar (KYD)", "value": "KYD"},
                    {"label": "Cedi (GHC)", "value": "GHC"},
                    {"label": "CFA Franc BCEAO (XOF)", "value": "XOF"},
                    {"label": "CFA Franc BEAC (XAF)", "value": "XAF"},
                    {"label": "CFP Franc (XPF)", "value": "XPF"},
                    {"label": "Chilean Peso (CLP)", "value": "CLP"},
                    {"label": "Codes specifically reserved for testing purposes (XTS)", "value": "XTS"},
                    {"label": "Colombian Peso (COP)", "value": "COP"},
                    {"label": "Comorian Franc  (KMF)", "value": "KMF"},
                    {"label": "Congolese Franc (CDF)", "value": "CDF"},
                    {"label": "Convertible Franc (BEC)", "value": "BEC"},
                    {"label": "Convertible Mark (BAM)", "value": "BAM"},
                    {"label": "Cordoba (NIC)", "value": "NIC"},
                    {"label": "Cordoba Oro (NIO)", "value": "NIO"},
                    {"label": "Costa Rican Colon (CRC)", "value": "CRC"},
                    {"label": "Croatian Dinar (HRD)", "value": "HRD"},
                    {"label": "Croatian Kuna (HRK)", "value": "HRK"},
                    {"label": "Cruzado (BRC)", "value": "BRC"},
                    {"label": "Cruzeiro (BRB)", "value": "BRB"},
                    {"label": "Cruzeiro (BRE)", "value": "BRE"},
                    {"label": "Cruzeiro Real (BRR)", "value": "BRR"},
                    {"label": "Cuban Peso (CUP)", "value": "CUP"},
                    {"label": "Cyprus Pound (CYP)", "value": "CYP"},
                    {"label": "Czech Koruna (CZK)", "value": "CZK"},
                    {"label": "Dalasi (GMD)", "value": "GMD"},
                    {"label": "Danish Krone (DKK)", "value": "DKK"},
                    {"label": "Denar (MKD)", "value": "MKD"},
                    {"label": "Deutsche Mark (DEM)", "value": "DEM"},
                    {"label": "Dinar (BAD)", "value": "BAD"},
                    {"label": "Djibouti Franc (DJF)", "value": "DJF"},
                    {"label": "Dobra (STN)", "value": "STN"},
                    {"label": "Dobra (STD)", "value": "STD"},
                    {"label": "Dominican Peso (DOP)", "value": "DOP"},
                    {"label": "Dong (VND)", "value": "VND"},
                    {"label": "Drachma (GRD)", "value": "GRD"},
                    {"label": "East Caribbean Dollar (XCD)", "value": "XCD"},
                    {"label": "Egyptian Pound (EGP)", "value": "EGP"},
                    {"label": "Ekwele (GQE)", "value": "GQE"},
                    {"label": "El Salvador Colon (SVC)", "value": "SVC"},
                    {"label": "Ethiopian Birr (ETB)", "value": "ETB"},
                    {"label": "Euro (EUR)", "value": "EUR"},
                    {"label": "European Currency Unit (E.C.U) (XEU)", "value": "XEU"},
                    {"label": "Falkland Islands Pound (FKP)", "value": "FKP"},
                    {"label": "Fiji Dollar (FJD)", "value": "FJD"},
                    {"label": "Financial Franc (BEL)", "value": "BEL"},
                    {"label": "Financial Rand (ZAL)", "value": "ZAL"},
                    {"label": "Forint (HUF)", "value": "HUF"},
                    {"label": "French Franc (FRF)", "value": "FRF"},
                    {"label": "Georgian Coupon (GEK)", "value": "GEK"},
                    {"label": "Ghana Cedi (GHS)", "value": "GHS"},
                    {"label": "Ghana Cedi (GHP)", "value": "GHP"},
                    {"label": "Gibraltar Pound (GIP)", "value": "GIP"},
                    {"label": "Gold (XAU)", "value": "XAU"},
                    {"label": "Gold-Franc (XFO)", "value": "XFO"},
                    {"label": "Gourde (HTG)", "value": "HTG"},
                    {"label": "Guarani (PYG)", "value": "PYG"},
                    {"label": "Guinea Escudo (GWE)", "value": "GWE"},
                    {"label": "Guinea-Bissau Peso (GWP)", "value": "GWP"},
                    {"label": "Guinean Franc (GNF)", "value": "GNF"},
                    {"label": "Guyana Dollar (GYD)", "value": "GYD"},
                    {"label": "Hong Kong Dollar (HKD)", "value": "HKD"},
                    {"label": "Hryvnia (UAH)", "value": "UAH"},
                    {"label": "Iceland Krona (ISK)", "value": "ISK"},
                    {"label": "Indian Rupee (INR)", "value": "INR"},
                    {"label": "Inti (PEI)", "value": "PEI"},
                    {"label": "Iranian Rial (IRR)", "value": "IRR"},
                    {"label": "Iraqi Dinar (IQD)", "value": "IQD"},
                    {"label": "Irish Pound (IEP)", "value": "IEP"},
                    {"label": "Italian Lira (ITL)", "value": "ITL"},
                    {"label": "Jamaican Dollar (JMD)", "value": "JMD"},
                    {"label": "Jordanian Dinar (JOD)", "value": "JOD"},
                    {"label": "Karbovanet (UAK)", "value": "UAK"},
                    {"label": "Kenyan Shilling (KES)", "value": "KES"},
                    {"label": "Kina (PGK)", "value": "PGK"},
                    {"label": "Koruna (CSK)", "value": "CSK"},
                    {"label": "Krona A/53 (CSJ)", "value": "CSJ"},
                    {"label": "Kroon (EEK)", "value": "EEK"},
                    {"label": "Kuna (HRK)", "value": "HRK"},
                    {"label": "Kuwaiti Dinar (KWD)", "value": "KWD"},
                    {"label": "Kwacha (MWK)", "value": "MWK"},
                    {"label": "Kwanza (AOA)", "value": "AOA"},
                    {"label": "Kwanza (AOK)", "value": "AOK"},
                    {"label": "Kwanza Reajustado (AOR)", "value": "AOR"},
                    {"label": "Kyat (MMK)", "value": "MMK"},
                    {"label": "Kyat (BUK)", "value": "BUK"},
                    {"label": "Lao Kip (LAK)", "value": "LAK"},
                    {"label": "Lari (GEL)", "value": "GEL"},
                    {"label": "Latvian Lats (LVL)", "value": "LVL"},
                    {"label": "Latvian Ruble (LVR)", "value": "LVR"},
                    {"label": "Lebanese Pound (LBP)", "value": "LBP"},
                    {"label": "Lek (ALL)", "value": "ALL"},
                    {"label": "Lempira (HNL)", "value": "HNL"},
                    {"label": "Leone (SLL)", "value": "SLL"},
                    {"label": "Leu A/52 (ROK)", "value": "ROK"},
                    {"label": "Lev (BGL)", "value": "BGL"},
                    {"label": "Lev A/52 (BGJ)", "value": "BGJ"},
                    {"label": "Lev A/62 (BGK)", "value": "BGK"},
                    {"label": "Liberian Dollar (LRD)", "value": "LRD"},
                    {"label": "Libyan Dinar (LYD)", "value": "LYD"},
                    {"label": "Lilangeni (SZL)", "value": "SZL"},
                    {"label": "Lithuanian Litas (LTL)", "value": "LTL"},
                    {"label": "Loti (LSL)", "value": "LSL"},
                    {"label": "Loti (LSM)", "value": "LSM"},
                    {"label": "Luxembourg Convertible Franc (LUC)", "value": "LUC"},
                    {"label": "Luxembourg Financial Franc (LUL)", "value": "LUL"},
                    {"label": "Luxembourg Franc (LUF)", "value": "LUF"},
                    {"label": "Malagasy Ariary (MGA)", "value": "MGA"},
                    {"label": "Malagasy Franc (MGF)", "value": "MGF"},
                    {"label": "Malawi Kwacha (MWK)", "value": "MWK"},
                    {"label": "Malaysian Ringgit (MYR)", "value": "MYR"},
                    {"label": "Maldive Rupee (MVQ)", "value": "MVQ"},
                    {"label": "Mali Franc (MLF)", "value": "MLF"},
                    {"label": "Maltese Lira (MTL)", "value": "MTL"},
                    {"label": "Maltese Pound (MTP)", "value": "MTP"},
                    {"label": "Mark der DDR (DDM)", "value": "DDM"},
                    {"label": "Markka (FIM)", "value": "FIM"},
                    {"label": "Mauritius Rupee (MUR)", "value": "MUR"},
                    {"label": "Mexican Peso (MXN)", "value": "MXN"},
                    {"label": "Mexican Peso (MXP)", "value": "MXP"},
                    {"label": "Mexican Unidad de Inversion (UDI) (MXV)", "value": "MXV"},
                    {"label": "Moldovan Leu (MDL)", "value": "MDL"},
                    {"label": "Moroccan Dirham (MAD)", "value": "MAD"},
                    {"label": "Mozambique Escudo (MZE)", "value": "MZE"},
                    {"label": "Mozambique Metical (MZN)", "value": "MZN"},
                    {"label": "Mozambique Metical (MZM)", "value": "MZM"},
                    {"label": "Mvdol (BOV)", "value": "BOV"},
                    {"label": "Naira (NGN)", "value": "NGN"},
                    {"label": "Nakfa (ERN)", "value": "ERN"},
                    {"label": "Namibia Dollar (NAD)", "value": "NAD"},
                    {"label": "Nepalese Rupee (NPR)", "value": "NPR"},
                    {"label": "Netherlands Antillean Guilder (ANG)", "value": "ANG"},
                    {"label": "Netherlands Guilder (NLG)", "value": "NLG"},
                    {"label": "New Cruzado (BRN)", "value": "BRN"},
                    {"label": "New Dinar (YUM)", "value": "YUM"},
                    {"label": "New Israeli Sheqel (ILS)", "value": "ILS"},
                    {"label": "New Kwanza (AON)", "value": "AON"},
                    {"label": "New Romanian Leu  (RON)", "value": "RON"},
                    {"label": "New Taiwan Dollar (TWD)", "value": "TWD"},
                    {"label": "New Turkish Lira (TRY)", "value": "TRY"},
                    {"label": "New Yugoslavian Dinar (YUD)", "value": "YUD"},
                    {"label": "New Zaire (ZRN)", "value": "ZRN"},
                    {"label": "New Zealand Dollar (NZD)", "value": "NZD"},
                    {"label": "Ngultrum (BTN)", "value": "BTN"},
                    {"label": "No universal currency ()", "value": ""},
                    {"label": "North Korean Won (KPW)", "value": "KPW"},
                    {"label": "Norwegian Krone (NOK)", "value": "NOK"},
                    {"label": "Nuevo Sol  (PEN)", "value": "PEN"},
                    {"label": "Old Dong (VNC)", "value": "VNC"},
                    {"label": "Old Krona (ISJ)", "value": "ISJ"},
                    {"label": "Old Lek (ALK)", "value": "ALK"},
                    {"label": "Old Leu (ROL)", "value": "ROL"},
                    {"label": "Old Shekel (ILR)", "value": "ILR"},
                    {"label": "Old Shilling (UGW)", "value": "UGW"},
                    {"label": "Old Turkish Lira (TRL)", "value": "TRL"},
                    {"label": "Old Uruguay Peso (UYN)", "value": "UYN"},
                    {"label": "Ouguiya (MRU)", "value": "MRU"},
                    {"label": "Ouguiya (MRO)", "value": "MRO"},
                    {"label": "Pa'anga (TOP)", "value": "TOP"},
                    {"label": "Pakistan Rupee (PKR)", "value": "PKR"},
                    {"label": "Palladium (XPD)", "value": "XPD"},
                    {"label": "Pataca (MOP)", "value": "MOP"},
                    {"label": "Pathet Lao Kip (LAJ)", "value": "LAJ"},
                    {"label": "Peso (ARY)", "value": "ARY"},
                    {"label": "Peso Argentino (ARP)", "value": "ARP"},
                    {"label": "Peso boliviano (BOP)", "value": "BOP"},
                    {"label": "Peso Convertible (CUC)", "value": "CUC"},
                    {"label": "Peso Uruguayo (UYU)", "value": "UYU"},
                    {"label": "Philippine Peso (PHP)", "value": "PHP"},
                    {"label": "Platinum (XPT)", "value": "XPT"},
                    {"label": "Portuguese Escudo (PTE)", "value": "PTE"},
                    {"label": "Pound (ILP)", "value": "ILP"},
                    {"label": "Pound Sterling (GBP)", "value": "GBP"},
                    {"label": "Pula (BWP)", "value": "BWP"},
                    {"label": "Qatari Rial (QAR)", "value": "QAR"},
                    {"label": "Quetzal (GTQ)", "value": "GTQ"},
                    {"label": "Rand (ZAR)", "value": "ZAR"},
                    {"label": "Rhodesian Dollar (RHD)", "value": "RHD"},
                    {"label": "Rhodesian Dollar (ZWC)", "value": "ZWC"},
                    {"label": "Rial Omani (OMR)", "value": "OMR"},
                    {"label": "Riel (KHR)", "value": "KHR"},
                    {"label": "RINET Funds Code (XRE)", "value": "XRE"},
                    {"label": "Romanian Leu (RON)", "value": "RON"},
                    {"label": "Rouble (SUR)", "value": "SUR"},
                    {"label": "Rufiyaa (MVR)", "value": "MVR"},
                    {"label": "Rupiah (IDR)", "value": "IDR"},
                    {"label": "Russian Ruble (RUB)", "value": "RUB"},
                    {"label": "Russian Ruble (RUR)", "value": "RUR"},
                    {"label": "Rwanda Franc (RWF)", "value": "RWF"},
                    {"label": "Saint Helena Pound (SHP)", "value": "SHP"},
                    {"label": "Saudi Riyal (SAR)", "value": "SAR"},
                    {"label": "Schilling (ATS)", "value": "ATS"},
                    {"label": "SDR (Special Drawing Right) (XDR)", "value": "XDR"},
                    {"label": "Serbian Dinar (RSD)", "value": "RSD"},
                    {"label": "Serbian Dinar (CSD)", "value": "CSD"},
                    {"label": "Seychelles Rupee (SCR)", "value": "SCR"},
                    {"label": "Silver (XAG)", "value": "XAG"},
                    {"label": "Singapore Dollar (SGD)", "value": "SGD"},
                    {"label": "Slovak Koruna (SKK)", "value": "SKK"},
                    {"label": "Sol (PEN)", "value": "PEN"},
                    {"label": "Sol (PEH)", "value": "PEH"},
                    {"label": "Sol (PES)", "value": "PES"},
                    {"label": "Solomon Islands Dollar (SBD)", "value": "SBD"},
                    {"label": "Som (KGS)", "value": "KGS"},
                    {"label": "Somali Shilling (SOS)", "value": "SOS"},
                    {"label": "Somoni (TJS)", "value": "TJS"},
                    {"label": "South Sudanese Pound (SSP)", "value": "SSP"},
                    {"label": "Spanish Peseta (ESP)", "value": "ESP"},
                    {"label": "Spanish Peseta (ESA)", "value": "ESA"},
                    {"label": "Sri Lanka Rupee (LKR)", "value": "LKR"},
                    {"label": "Sucre (XSU)", "value": "XSU"},
                    {"label": "Sucre (ECS)", "value": "ECS"},
                    {"label": "Sudanese Dinar (SDD)", "value": "SDD"},
                    {"label": "Sudanese Pound (SDG)", "value": "SDG"},
                    {"label": "Sudanese Pound (SDP)", "value": "SDP"},
                    {"label": "Surinam Dollar (SRD)", "value": "SRD"},
                    {"label": "Surinam Guilder (SRG)", "value": "SRG"},
                    {"label": "Swedish Krona (SEK)", "value": "SEK"},
                    {"label": "Swiss Franc (CHF)", "value": "CHF"},
                    {"label": "Syli (GNE)", "value": "GNE"},
                    {"label": "Syli (GNS)", "value": "GNS"},
                    {"label": "Syrian Pound (SYP)", "value": "SYP"},
                    {"label": "Tajik Ruble (TJR)", "value": "TJR"},
                    {"label": "Taka (BDT)", "value": "BDT"},
                    {"label": "Tala (WST)", "value": "WST"},
                    {"label": "Talonas (LTT)", "value": "LTT"},
                    {"label": "Tanzanian Shilling (TZS)", "value": "TZS"},
                    {"label": "Tenge (KZT)", "value": "KZT"},
                    {"label": "Timor Escudo (TPE)", "value": "TPE"},
                    {"label": "Tolar (SIT)", "value": "SIT"},
                    {"label": "Trinidad and Tobago Dollar (TTD)", "value": "TTD"},
                    {"label": "Tugrik (MNT)", "value": "MNT"},
                    {"label": "Tunisian Dinar (TND)", "value": "TND"},
                    {"label": "Turkish Lira (TRY)", "value": "TRY"},
                    {"label": "Turkmenistan Manat (TMM)", "value": "TMM"},
                    {"label": "Turkmenistan New Manat (TMT)", "value": "TMT"},
                    {"label": "UAE Dirham (AED)", "value": "AED"},
                    {"label": "Uganda Shilling (UGX)", "value": "UGX"},
                    {"label": "Uganda Shilling (UGS)", "value": "UGS"},
                    {"label": "UIC-Franc (XFU)", "value": "XFU"},
                    {"label": "Unidad de Fomento (CLF)", "value": "CLF"},
                    {"label": "Unidad de Valor Constante (UVC) (ECV)", "value": "ECV"},
                    {"label": "Unidad de Valor Real (COU)", "value": "COU"},
                    {"label": "Unidad Previsional (UYW)", "value": "UYW"},
                    {"label": "Uruguay Peso en Unidades Indexadas (UI) (UYI)", "value": "UYI"},
                    {"label": "Uruguayan Peso (UYP)", "value": "UYP"},
                    {"label": "US Dollar (USD)", "value": "USD"},
                    {"label": "US Dollar (Next day) (USN)", "value": "USN"},
                    {"label": "US Dollar (Same day) (USS)", "value": "USS"},
                    {"label": "Uzbekistan Sum (UZS)", "value": "UZS"},
                    {"label": "Vatu (VUV)", "value": "VUV"},
                    {"label": "WIR Euro (CHE)", "value": "CHE"},
                    {"label": "WIR Franc (CHW)", "value": "CHW"},
                    {"label": "WIR Franc (for electronic) (CHC)", "value": "CHC"},
                    {"label": "Won (KRW)", "value": "KRW"},
                    {"label": "Yemeni Dinar (YDD)", "value": "YDD"},
                    {"label": "Yemeni Rial (YER)", "value": "YER"},
                    {"label": "Yen (JPY)", "value": "JPY"},
                    {"label": "Yuan Renminbi (CNY)", "value": "CNY"},
                    {"label": "Yugoslavian Dinar (YUN)", "value": "YUN"},
                    {"label": "Zaire (ZRZ)", "value": "ZRZ"},
                    {"label": "Zambian Kwacha (ZMW)", "value": "ZMW"},
                    {"label": "Zambian Kwacha (ZMK)", "value": "ZMK"},
                    {"label": "Zimbabwe Dollar (ZWL)", "value": "ZWL"},
                    {"label": "Zimbabwe Dollar (ZWD)", "value": "ZWD"},
                    {"label": "Zimbabwe Dollar (ZWR)", "value": "ZWR"},
                    {"label": "Zimbabwe Dollar (new) (ZWN)", "value": "ZWN"},
                    {"label": "Zimbabwe Dollar (old) (ZWD)", "value": "ZWD"},
                    {"label": "Zloty (PLN)", "value": "PLN"},
                    {"label": "Zloty (PLZ)", "value": "PLZ"}
                ]}
            />
        </PanelRow>}</>,
        <PanelRow>
            <TextControl
                type={"Number"}
                label={__("Decimal Points","dg")}
                onChange={onDecimalChange}
                value={format.minimumFractionDigits}
            />
        </PanelRow>

    ]
}

export default Format