//require("./block-styles/index")
//require("./block-styles/columns")
require("./tabbed-posts")
require("./charts")
require("./featured-tabs")
require("./filter")
require("./inline-list")
require("./page-gallery")
require("./page-modules")
require("./post-carousel")
require("./tabbed-posts")
require("./newsletter")
require("./showcase-form")
require("./ailments-body")
require("./downloads")
require("./pdf")
require("./map")
require("./redirect")
require("./data-filters-reset")
require("./format-bar/infotooltip")
require("./format-bar/references")
require("./time-line")
require("./new-time-line")
require("./measures")
require("./vertical-featured-tabs")
require("./child-pages-navigator")
require("./d3Map")
require("./parallax-container")
require("./wrapped-component")
require("../../../../custom/wp-customizer/blocks/index")




