fastcgi_cache_path /var/cache/nginx/wp levels=1 keys_zone=wp:128k inactive=1h;
proxy_cache_path /var/cache/nginx/render levels=2 keys_zone=render:256k inactive=30d;
proxy_cache render;
proxy_cache_key $uri;

upstream php_fcgi {
  server wordpress:9000;
}

map $http_user_agent $prerender {
  default 0;
  ~[Bb]ot\b 1;
  ~[Ss]pider\b 1;
  ~\bYandex 1;
  ~WhatsApp 1;
  ~***REMOVED*** 1;
  ~***REMOVED*** 1;
  ~*embedly 1;
  ~Quora 1;
  ~*outbrain 1;
  ~*pinterest\b 1;
  ~*vkshare 1;
  ~*w3c_validator 1;
}

server {
  listen 80 default_server;
  listen [::]:80 default_server;
  client_header_buffer_size 5120k;
  large_client_header_buffers 16 5120k;
  client_max_body_size 30M;
  gzip on;
  gzip_vary on;

  root /var/www/static;

  if ($args ~ "_escaped_fragment_") {
    set $prerender 1;
  }

  if ($uri ~* "\.(css|jpe?g|js(on)?|png|xml|gif|pdf|(doc|xls|ppt)x?)$") {
    set $prerender 0;
  }



  location / {
    try_files $uri $uri/ /index.html;
    proxy_set_header Accept-Encoding '';
    proxy_set_header Origin '';
    proxy_ignore_headers Vary;
    proxy_cache_valid 30d;
  }



  location /wp {
    alias /var/www/html;
    index index.php;
    # https://trac.nginx.org/nginx/ticket/97
    # bug in Nginx worked around by doubling location prefix:
    try_files $uri $uri/ /wp/wp/index.php$is_args$args;
    client_max_body_size 30M;

    location ~ \.php$ {
      include fastcgi.conf;
      fastcgi_split_path_info ^/wp(.+\.php)(.*)$;
      fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
      fastcgi_pass php_fcgi;
      fastcgi_cache wp;
      fastcgi_cache_key $request_uri;
      fastcgi_cache_valid 15m;
    }
  }






location /api/ {

       # Preflighted requests
       if ($request_method = OPTIONS ) {
         add_header "Access-Control-Allow-Origin"  *;
         add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS, HEAD";
         add_header "Access-Control-Allow-Headers" "Authorization, Origin, X-Requested-With, Content-Type, Accept";
         return 200;
       }

      gunzip on;
      client_max_body_size 30M;
      proxy_set_header X-Forwarded-Host $host:$server_port;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-Prefix /api;
      proxy_pass http://zuul:8762/;
  }

}
