import {useBlockProps} from '@wordpress/block-editor';
import {InnerBlocks} from '@wordpress/editor'; // or wp.editor
const SaveComponent = (props) => {
    const {
        ***REMOVED***, setAttributes, attributes: {
            height,
            width,
            type,
            groupMode,
            bottomLegend,
            leftLegend,
            scheme,
            colorBy,
            dimension1,
            dimension2,
            dimension3,
            dualMode,
            ***REMOVED***,
            ***REMOVED***,
            ***REMOVED***,
            dataSource,
            ***REMOVED***,
            marginLeft,
            marginTop,
            marginRight,
            marginBottom,
            showLegends,
            legendLabel,
            app,
            measures,
            tickColor,
            tickRotation,
            offsetText,
            format,
            decimals,
            currency,
            tooltipHTML,
            csv,
            startAngle,
            endAngle,
            layout,
            reverse,
            offsetY,
            ***REMOVED***,
            csvLineColor,
            ***REMOVED***,
            csvLineTitle,
            ***REMOVED***,
            group,
            maxValue,
            valueScale,
            filters,
            swap,
            noDataMessage,
            barColor,
            ***REMOVED***,
            fixedMaxValue,
            fixedMinValue,
            barPadding,
            ***REMOVED***,
            ***REMOVED***,
            showGrid,
            ***REMOVED***,
            ***REMOVED***,
            ***REMOVED***,
            ***REMOVED***,
            useCheckBoxBackground,
            xLabelColor = "#000000",
            barLabelColor = "#000000",
            ***REMOVED*** = "#000000",
            ***REMOVED***,
            showTickLine,
            manualColors,
            showRightAxis,
            rightLegend,
            offsetRight,
            offsetBottom,
            hiddenBars,
            enableArea,
            ***REMOVED***,
            ***REMOVED***,
            ***REMOVED***,
            showPoints,
            ***REMOVED***,
            centerLabel,
            showArcLabels,
            ***REMOVED***,
            slicePadding,
            centerLabelFontWeight,
            ***REMOVED***,
            ***REMOVED***,
            ***REMOVED***,
            ***REMOVED***,
            ***REMOVED***,
            ***REMOVED***,
            groupTotalFixedPosition,
            ***REMOVED***,
            groupTotalLabelOffset,
            tooltipEnableMarkdown,
            ***REMOVED***,
            ***REMOVED***,
            enableGridY,
            enableGridX,
            overallLabel,
            overlays,
            minMaxClamp,
            reverseLegend,
            sort,
            sortReverse,
            ***REMOVED***,
            radarCurve,
            ***REMOVED***,
            ***REMOVED***,
            ***REMOVED***,
            ***REMOVED***,
            ***REMOVED***,
            ***REMOVED***,
            radarDotSize,
            ***REMOVED***,
            ***REMOVED***,
            ***REMOVED***,
            ***REMOVED***,
            ***REMOVED***,
            previewMode
        }
    } = props;
    const blockProps = useBlockProps.save({
        className: 'viz component chart'
    });

    const levels = [dimension1, dimension2, dimension3]
    const source = levels.filter(l => l != 'none' && l != null).join('/')

    return (
        <div {...blockProps} className={"viz-component"}
             data-component={"chart"}
             data-height={height}
             data-type={type}
             data-source={source}
             data-dvz-proxy-dataset-id={***REMOVED***}
             data-dimension1={dimension1}
             data-dimension2={dimension2}
             data-dimension3={dimension3}
             data-color-by={colorBy}
             data-scheme={scheme}
             data-group-mode={groupMode}
             data-left-legend={leftLegend}
             data-dualMode={dualMode}
             data-bottom-legend={bottomLegend}
             data-toggle-info-label={***REMOVED***}
             data-toggle-chart-label={***REMOVED***}
             data-data-source-label={***REMOVED***}
             data-chart-data-source={dataSource}
             data-margin-left={marginLeft}
             data-margin-top={marginTop}
             data-margin-right={marginRight}
             data-margin-bottom={marginBottom}
             data-show-legends={showLegends}
             data-legend-position={***REMOVED***}
             data-app={app}
             data-tick-rotation={tickRotation}
             data-offset-text={offsetText}
             data-tick-color={tickColor}
             data-line-layer-enabled={***REMOVED***}
             data-measures={***REMOVED***(JSON.stringify(measures))}
             data-format={***REMOVED***(JSON.stringify(format))}
             data-decimals={decimals}
             data-currency={currency}
             data-csv={csv}
             data-tooltip-html={***REMOVED***(tooltipHTML)}
             data-start-angle={startAngle}
             data-end-angle={endAngle}
             data-layout={layout}
             data-reverse={reverse}
             data-offset-y={offsetY}
            //data-csv-line-layer-data={***REMOVED***}
            //data-csv-line-color={csvLineColor}
            // data-csv-line-tooltip={***REMOVED***}
            //data-csv-line-title={csvLineTitle}
             data-group={group}
             data-max-value={maxValue}
             data-value-scale={valueScale}
             data-filters={***REMOVED***(JSON.stringify(filters))}
             data-swap={swap}
             data-no-data-message={noDataMessage}
             data-legend-label={legendLabel}
             data-bar-color={barColor}
             data-override-tick-color={***REMOVED***}
             data-fixed-min-value={fixedMinValue}
             data-fixed-max-value={fixedMaxValue}
             data-bar-padding={barPadding}
             data-bar-label-position={***REMOVED***}
             data-line-label-position={***REMOVED***}
             data-show-grid={showGrid}
             data-include-overall={***REMOVED***}
             data-tooltip-enabled={***REMOVED***}
             data-x-label-color={xLabelColor}
             data-bar-label-color={barLabelColor}
             data-bar-inner-padding={***REMOVED***}
             data-use-label-background={***REMOVED***}
             data-use-check-box-background={useCheckBoxBackground}
             data-legend-label-color={***REMOVED***}
             data-highlight-xaxis-line={***REMOVED***}
             data-show-tick-line={showTickLine}
             data-show-right-axis={showRightAxis}
             data-right-legend={rightLegend}
             data-offset-right={offsetRight}
             data-offset-bottom={offsetBottom}
             data-enable-area={enableArea}
             data-area-shading-criteria={***REMOVED***}
             data-area-lower-bound={***REMOVED***}
             data-area-upper-bound={***REMOVED***}
             data-show-points={showPoints}
             data-hidden-bars={hiddenBars.join(',')}
             data-confidence-intervals={***REMOVED***(JSON.stringify(***REMOVED***))}
             data-manual-colors={***REMOVED***(JSON.stringify(manualColors))}
             data-group-total-measure={***REMOVED***}
             data-show-group-total={***REMOVED***}
             data-group-total-label-offset={groupTotalLabelOffset}
             data-group-total-format={***REMOVED***(JSON.stringify(***REMOVED***))}
             data-group-total-fixed-position={groupTotalFixedPosition}
             data-group-total-label={***REMOVED***}
             data-show-arc-labels={showArcLabels}
             data-show-arc-link-labels={***REMOVED***}
             data-slice-padding={slicePadding}
             data-center-label={centerLabel}
             data-center-label-font-weight={centerLabelFontWeight}
             data-center-label-font-size={***REMOVED***}
             data-center-label-xoffset={***REMOVED***}
             data-center-label-yoffset={***REMOVED***}
             data-tooltip-enable-markdown={tooltipEnableMarkdown}
             data-y-axis-tick-values={***REMOVED***}
             data-x-axis-tick-values={***REMOVED***}
             data-enable-grid-y={enableGridY}
             data-enable-grid-x={enableGridX}
             data-overall-label={overallLabel}
             data-overlays={***REMOVED***(JSON.stringify(overlays))}
             data-min-max-clamp={minMaxClamp}
             data-reverse-legend={reverseLegend}
             data-sort={sort}
             data-sort-reverse={sortReverse}
             data-***REMOVED***={***REMOVED***}
             data-radar-curve={radarCurve}
             data-radar-fill-opacity={***REMOVED***}
             data-radar-border-width={***REMOVED***}
             data-radar-grid-levels={***REMOVED***}
             data-radar-grid-shape={***REMOVED***}
             data-radar-grid-label-offset={***REMOVED***}
             data-radar-enable-dots={***REMOVED***}
             data-radar-dot-size={radarDotSize}
             data-radar-enable-dot-label={***REMOVED***}
             data-radar-dot-label-offset={***REMOVED***}
             data-show-percentage={***REMOVED***}
             data-preview-mode={previewMode}
             data-mobile-customization={***REMOVED***(JSON.stringify(***REMOVED***))}
             >
            <InnerBlocks.Content/>
        </div>
    );
}

export default SaveComponent

