name: Test on PR

on:
  pull_request:
    paths:
      - "packages/commons/**"
      - "packages/create-wp-customizer/**"
      - "packages/upgrade-wp-customizer/**"
      - "data-viz-wordpress/**"
      - "package.json"
      - "pnpm-lock.yaml"
    
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run PNPM Build
        run: pnpm run build